threadtest: *.cxx
	cl /Od /I "../../../libmutil/include" /D "WIN32" /D "DEBUG_OUTPUT" /D "_DEBUG" /D "_WINDOWS" /D "_MBCS" /Gm /EHsc /RTC1 /MTd /GR  /D "_CONSOLE" /Fo"out/" /Fd"out/vc70.pdb" /W3 /nologo /c /Wp64 /ZI /TP *.cxx
	link /OUT:"threadtext.exe" /INCREMENTAL /NOLOGO /LIBPATH:"..\..\..\libmutil\w32out" /DEBUG /PDB:"threadtext.pdb" /SUBSYSTEM:CONSOLE /IMPLIB:"threadtest.lib" /MACHINE:X86   kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib Ws2_32.lib libmutil.lib out/*.obj
clean:
	del w32out\*
