######################################################################
# Automatically generated by qmake (2.00a) Sun Jun 29 16:40:52 2003
######################################################################

TEMPLATE = app
CONFIG -= moc
DEPENDPATH += old
INCLUDEPATH += .

# Input
SOURCES += eve_qtgui.cxx voip_eve.cxx
