# AM_MINISIP_CHECK_LIBMSTUN(VERSION)
# ------------------------------------
AC_DEFUN([AM_MINISIP_CHECK_LIBMSTUN],[ 
	AC_REQUIRE([AM_MINISIP_CHECK_LIBMNETUTIL]) dnl
dnl	AC_REQUIRE([AM_MINISIP_CHECK_OPENSSL]) dnl
	AC_MINISIP_WITH_ARG(MSTUN, mstun, libmstun, $1, [REQUIRED], [])
	AC_MINISIP_CHECK_LIBRARY(MSTUN, libmstun, config.h, mstun)
  ])
# End of AM_MINISIP_CHECK_LIBMSTUN
#
