#! /bin/sh

##  bootstrap file - borrowed from VideoLAN's libdvdplay 
##  original verion by Sam Hocevar <sam@zoy.org>

set -x
set -e

# Get a sane environment, just in case
LANG=C
export LANG
CYGWIN=binmode
export CYGWIN

# Check for automake
amvers="no"
if automake-1.7 --version >/dev/null 2>&1; then
  amvers="-1.7"
elif automake --version > /dev/null 2>&1; then
  amvers="`automake --version | sed -e '1s/[^0-9]*//' -e q`"
  if expr "$amvers" "<" "1.7" > /dev/null 2>&1; then
    amvers="no"
  else
    amvers=""
  fi
fi

if test "$amvers" = "no"; then
  set +x
  echo "$0: you need automake version 1.7 or later"
  exit 1
fi


# Remove old cruft
rm -f aclocal.m4 configure config.guess config.log config.sub config.cache config.h.in config.h compile ltmain.sh libtool ltconfig missing mkinstalldirs depcomp install-sh
rm -Rf autom4te.cache

aclocal${amvers}

autoconf
autoheader
automake${amvers} --add-missing --copy

