# AM_MINISIP_CHECK_LIBZRTP(VERSION)
# ----------------------------------
AC_DEFUN([AM_MINISIP_CHECK_LIBZRTPCPP],[
    AC_REQUIRE([AM_MINISIP_CHECK_LIBMUTIL]) dnl
    AC_MINISIP_WITH_ARG(ZRTP, zrtpcpp, libzrtpcpp, $1, [REQUIRED])
    AC_MINISIP_CHECK_LIBRARY(ZRTP, libzrtpcpp, ZRtp.h, zrtpcpp)
  ])
# End of AM_MINISIP_CHECK_LIBZRTPCPP
#
